version: '3.4'

services:
  sql_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "BigPassw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:  
      - ./data/mssql:/var/opt/mssql3  

  calendarevents:
    image: ${DOCKER_REGISTRY-}calendarevents
    build:
      context: .
      dockerfile: CalendarEvent/Dockerfile
    depends_on:
      - sql_db