version: '3.4'

services:
  sql_db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "BigPassw0rd"
        ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:  
      - ./data/mssql:/var/opt/mssql3  

  calendarevents:
    image: ${DOCKER_REGISTRY-}calendarevents
    build:
      context: .
      dockerfile: CalendarEvent/Dockerfile
    environment:
      -CONNECTION_STRING: "Server=sql_db;Database=CalendarDB;User=sa;Password=BigPassw0rd;"
    depends_on:
      - sql_db

  calendareventsclient:
    image: ${DOCKER_REGISTRY-}client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - calendarevents