version: '3.4'

services:
  api:
    image: "shaharshokrani/calendarevents_api:firstpush"
    build:
      context: .
      dockerfile: CalendarEvents.API/API_Dockerfile
    environment:
      - DatabaseServer=api_db
      - DatabaseName=CalendarEventsApiDB
      - DatabasePort=1433
      - DatabaseUser=sa
      - DatabasePassword=<YourStrong@Passw0rd>    
      - ASPNETCORE_ENVIRONMENT=Development
      - Authority=http://idp
      - ASPNETCORE_Kestrel__Certificates__Default__Password=certpassword
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    container_name: calendarevents_api_container
    ports:
      - "5000:80"
    networks:
      - back-tier
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - api_db
      - idp

  api_db:
    image: "shaharshokrani/calendarevents_api_db:firstpush"
    build:
      context: .
      dockerfile: CalendarEvents.API/DB_Dockerfile
    ports:
      - "1443:1433"
    environment:
      - SA_PASSWORD=<YourStrong@Passw0rd>
      - ACCEPT_EULA=Y    
    container_name: calendarevents_api_db_container
    networks:
      - back-tier

  idp:
    image: "shaharshokrani/calendarevents_api_db:firstpush"
    environment:      
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: calendarevents_idp_container
    ports:
      - "5001:80"      
    networks:
      - back-tier

networks:
  back-tier:  